<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Dr.&nbsp;Christos Vrakopoulos">
  <title>The Far Right – Far-Right in the United Kingdom</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-1f88f5497b01d3f5c3951ff3ae868544.css">
  <link rel="stylesheet" href="custom.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Far-Right in the United Kingdom</h1>
  <p class="subtitle">The Far Right (Week 3)</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Christos Vrakopoulos 
</div>
</div>
</div>

</section>
<section id="todays-lecture" class="slide level2">
<h2>Today’s Lecture</h2>
<ul>
<li class="fragment"><strong>Part 1:</strong> The Puzzle - Demand Without Breakthrough</li>
<li class="fragment"><strong>Part 2:</strong> Three Trajectories - BNP, UKIP, Reform</li>
<li class="fragment"><strong>Part 3:</strong> Who Votes Far-Right in the UK?</li>
<li class="fragment"><strong>Part 4:</strong> Implications for Theory</li>
</ul>
</section>
<section>
<section id="part-1-the-puzzle" class="title-slide slide level1 center">
<h1>Part 1: The Puzzle</h1>

</section>
<section id="demand-without-breakthrough-19682010" class="slide level2">
<h2>Demand Without Breakthrough (1968–2010)</h2>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="enoch-powell-april-1968">Enoch Powell, April 1968</h3>
<div class="fragment fade-in">
<p>Conservative Shadow Cabinet: <strong>“Rivers of Blood” speech</strong></p>
</div>
<div class="fragment fade-in">
<p>Topic: Immigration threat to British culture</p>
</div>
<div class="fragment fade-in">
<p>Polls and letters suggest broad popular sympathy with Powell’s message</p>
</div>
<div class="fragment fade-in">
<p>Political response: Isolated, forced to resign from shadow cabinet</p>
</div>
</div><div class="column" style="width:50%;">
<h3 id="the-consequence">The consequence</h3>
<div class="fragment fade-in">
<p>Powell’s 1968 speech sharply raised the salience of immigration.</p>
</div>
<div class="fragment fade-in">
<p>But, as Evans &amp; Mellon argue, this did not crystallize into a new durable cleavage or party alignment in the 1970s–80s.</p>
</div>
<div class="fragment fade-in">
<p>Thatcher selectively adopted “Powellite” themes in a more measured form, undercutting the electoral space for the National Front.</p>
</div>
<div class="fragment fade-in">
<p>NF/BNP links to neo-Nazism and post-war fascism made them less socially acceptable than many continental radical right parties, limiting their breakthrough potential.</p>
</div>
</div></div>
</section>
<section id="what-happened-next-1970s2000s" class="slide level2">
<h2>What happened next (1970s–2000s)?</h2>
<div class="fragment fade-in">
<p>National Front (1967-): Peak <strong>1.4% (1979)</strong></p>
</div>
<div class="fragment fade-in">
<p>BNP (1982-): Peak <strong>1.5% (2009)</strong> + <strong>2 MEPs</strong></p>
</div>
<div class="fragment fade-in">
<h4 id="the-puzzle">The Puzzle</h4>
</div>
<div class="fragment fade-in">
<p>Why did strong anti-immigration sentiment persist for 40+ years without a successful radical right party?</p>
</div>
</section>
<section id="same-demand-divergent-party-trajectories" class="slide level2">
<h2>Same Demand, Divergent Party Trajectories</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Election</th>
<th>BNP Votes</th>
<th>BNP %</th>
<th>UKIP Votes</th>
<th>UKIP %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1997</strong></td>
<td>35,832</td>
<td>1.4%</td>
<td>106,028</td>
<td>1.1%</td>
</tr>
<tr class="even">
<td><strong>2001</strong></td>
<td>47,129</td>
<td>3.9%</td>
<td>380,575</td>
<td>2.2%</td>
</tr>
<tr class="odd">
<td><strong>2005</strong></td>
<td>192,746</td>
<td>4.3%</td>
<td>603,298</td>
<td>2.8%</td>
</tr>
<tr class="even">
<td><strong>2010</strong></td>
<td>563,743</td>
<td><strong>3.8%</strong></td>
<td>919,546</td>
<td><strong>3.5%</strong></td>
</tr>
<tr class="odd">
<td><strong>2015</strong></td>
<td>1,667</td>
<td><strong>0.5%</strong></td>
<td>3,881,129</td>
<td><strong>13.2%</strong></td>
</tr>
</tbody>
</table>
<div class="fragment fade-in">
<p>Indicators of underlying immigration/Europe scepticism change slowly, yet party fortunes diverge rapidly.</p>
</div>
</section>
<section id="three-questions" class="slide level2">
<h2>Three Questions</h2>
<ol type="1">
<li class="fragment"><strong>Supply-side failure (1968–2010):</strong> Why did strong public demand not produce a breakthrough?
<ul>
<li class="fragment">Was it <strong>extremism</strong>? (NF/BNP too radical, organisationally weak)</li>
<li class="fragment">Was it <strong>mainstream closure</strong>? (Conservatives “stole the issue”)</li>
<li class="fragment">Or an <strong>interaction of both</strong>?</li>
</ul></li>
<li class="fragment"><strong>Supply-side success (2010–2016):</strong> What changed to enable breakthrough?
<ul>
<li class="fragment">Which party finally succeeded, and why UKIP rather than BNP?</li>
<li class="fragment">Which <strong>strategic choices</strong> mattered (issue focus, leadership, moderation, organisation)?</li>
</ul></li>
<li class="fragment"><strong>The paradox: electoral marginality, policy victory</strong>
<ul>
<li class="fragment">Just <strong>1 seat</strong> in Westminster</li>
<li class="fragment">Yet forced a <strong>national referendum</strong></li>
<li class="fragment">Yet helped <strong>reshape the country’s long‑term trajectory</strong></li>
</ul></li>
</ol>
</section></section>
<section>
<section id="part-2-three-trajectories" class="title-slide slide level1 center">
<h1>Part 2: Three Trajectories</h1>

</section>
<section id="why-bnp-failed-locked-in-extremism" class="slide level2">
<h2>Why BNP Failed: Locked in Extremism</h2>
<ol type="1">
<li class="fragment"><strong>Geographic concentration</strong>
<ul>
<li class="fragment">563,743 votes (2010) but only 3.8% nationally</li>
<li class="fragment">88 council seats (2005) on just 4.3% vote share</li>
<li class="fragment">Support heavily clustered in a few local strongholds</li>
</ul></li>
<li class="fragment"><strong>Extremism trap</strong>
<ul>
<li class="fragment">Neo-Nazi imagery kept party on the hardline fringe</li>
<li class="fragment">Could hit 16% in local “true believer” areas</li>
<li class="fragment">But could never reach 4%+ nationally (repelled moderates)</li>
</ul></li>
<li class="fragment"><strong>Unable to moderate</strong>
<ul>
<li class="fragment">Unlike UKIP, couldn’t soften message without losing core identity</li>
<li class="fragment">Fascist heritage blocked “respectable” rebranding</li>
<li class="fragment">Strategically stuck: need extremism to survive, but extremism blocks growth</li>
</ul></li>
</ol>
</section>
<section id="why-ukip-succeeded-strategic-repositioning" class="slide level2">
<h2>Why UKIP Succeeded: Strategic Repositioning</h2>
<ol type="1">
<li class="fragment"><strong>Framing shift:</strong>
<ul>
<li class="fragment"><strong>BNP:</strong> “British culture threatened by non-white immigrants” (racialist)</li>
<li class="fragment"><strong>UKIP:</strong> “Britain’s sovereignty threatened by Brussels” (Eurosceptic)</li>
</ul></li>
<li class="fragment"><strong>Image matters:</strong>
<ul>
<li class="fragment"><strong>BNP:</strong> Perceived Neo-Nazi associations, skinhead base, paramilitary</li>
<li class="fragment"><strong>UKIP:</strong> Farage in suits, professional media, mainstream</li>
</ul></li>
<li class="fragment"><strong>Anti-immigration reframed:</strong>
<ul>
<li class="fragment"><strong>BNP:</strong> “Racial threat” (extremist appeal only)</li>
<li class="fragment"><strong>UKIP:</strong> “Public service pressure, population control” (moderate appeal)</li>
</ul></li>
<li class="fragment"><strong>Result:</strong>
<ul>
<li class="fragment">Same underlying demand</li>
<li class="fragment">Completely different supply</li>
<li class="fragment">By 2015, access to roughly 6.8x more voters</li>
</ul></li>
</ol>
</section>
<section id="the-paradox-13.2-votes-1-seat-won-brexit" class="slide level2">
<h2>The Paradox: 13.2% Votes, 1 Seat, Won Brexit</h2>
<ol type="1">
<li class="fragment"><strong>Electoral system effect</strong>
<ul>
<li class="fragment">2014 EP (PR): 26.6% → 24 MEPs</li>
<li class="fragment">2015 GE (FPTP): 13.2% → 1 MP</li>
<li class="fragment">Same electorate, different rules → radically different representation</li>
</ul></li>
<li class="fragment"><strong>Electorally weak, but policy victory</strong>
<ul>
<li class="fragment">Only 1 seat in Westminster</li>
<li class="fragment">Yet: Pushed Conservatives into promising a referendum (2013)</li>
<li class="fragment">Yet: Helped set the agenda for the 2016 Brexit vote</li>
<li class="fragment">→ Electoral marginality ≠ policy irrelevance</li>
</ul></li>
<li class="fragment"><strong>Key insight</strong>
<ul>
<li class="fragment">Non‑electoral pathways of influence: agenda‑setting, intra‑party pressure, media</li>
<li class="fragment">Far‑right success is not just about seats, but about shaping options</li>
</ul></li>
</ol>
</section>
<section id="why-ukip-declined-why-reform-emerged-same-demand-new-vessel" class="slide level2">
<h2>Why UKIP Declined, Why Reform Emerged (Same Demand, New Vessel)</h2>
<div class="column" style="width:50%;">
<div class="fragment fade-in">
<h4 id="ukip-2010-2015---breakthrough-and-fulfilment">UKIP 2010-2015 - Breakthrough and fulfilment</h4>
</div>
<ul>
<li class="fragment">Forced EU referendum onto agenda</li>
<li class="fragment">Became main vehicle for Brexit demand</li>
<li class="fragment">Policy goal achieved in 2016 → mission accomplished</li>
</ul>
<div class="fragment fade-in">
<h4 id="ukip-2016-2019-redundancy-and-collapse">UKIP 2016-2019 – Redundancy and collapse</h4>
</div>
<ul>
<li class="fragment">Core issue (EU membership) removed from agenda</li>
<li class="fragment">Leadership crises and party infighting</li>
<li class="fragment">Vote share and organisation rapidly disintegrate</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment fade-in">
<h4 id="reform-2022-2024-successor-party">Reform 2022-2024 – Successor party</h4>
</div>
<ul>
<li class="fragment">Farage returns with new vehicle (Clacton 2024)</li>
<li class="fragment">Conservative government instability (Brexit fallout, Covid, Truss, etc.)</li>
<li class="fragment">Rising Conservative voter dissatisfaction on immigration, taxes, “betrayed Brexit”</li>
<li class="fragment">Same underlying demand (nationalist, anti‑establishment, anti‑immigration)</li>
<li class="fragment">New credible supply to channel it</li>
</ul>
<div class="fragment fade-in">
<h4 id="pattern">Pattern</h4>
<ul>
<li class="fragment">Underlying demand is structural and durable</li>
<li class="fragment">Party vehicles are temporary and recyclable (roughly every 15–20 years)</li>
</ul>
</div>
</div></section>
<section id="reform-breaks-into-scotland-holyrood-constituency-vote" class="slide level2">
<h2>Reform Breaks into Scotland: Holyrood Constituency Vote</h2>

<img data-src="images/constituency.png" class="r-stretch quarto-figure-center"><p class="caption">Holyrood constituency vote intention, 2022-2026</p><p>Source: Scottish Election Study, Scottish Opinion Monitor</p>
<p><strong>Question:</strong> Why NOW? Scotland uses PR (not constrained by FPTP). This is pure demand/supply question.</p>
<aside class="notes">
<p>Same pattern in constituency vote: Reform absent → emerges → grows rapidly</p>
<p>Note: Both graphs show methodology change in Oct 2024 (when Reform formally added to options).</p>
<p>Before Oct 2024: Reform likely clustered in “Other”—so emergence is partly definitional (added as option) but also real (rapid growth once visible).</p>
<p>The answer comes next: Scotland’s political space opens when the SNP-Tory symbiosis breaks and constitutional salience decays. This is supply-side theory playing out regionally.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-scotlands-political-space-opens-now-vampa-et-al.-forthcoming-in-political-studies" class="slide level2">
<h2>Why Scotland’s Political Space Opens Now (Vampa et al.&nbsp;Forthcoming in Political Studies)</h2>
<div class="column" style="width:50%;">
<div class="fragment fade-in">
<h4 id="years-1998-2018-snp-tory-symbiosis-on-constitutional-issues">20 years (1998-2018): SNP-Tory symbiosis on constitutional issues</h4>
</div>
<ul>
<li class="fragment"><p>SNP: “Vote for us for independence”</p></li>
<li class="fragment"><p>Conservatives: “Vote for us to defend the Union and deliver Brexit”</p></li>
<li class="fragment"><p>Independence vs.&nbsp;Union becomes the dominant cleavage, structuring party competition and voter alignments</p></li>
<li class="fragment"><p>Other conflicts (immigration, tax, anti‑establishment sentiment) are submerged beneath the sovereignty question</p></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="fragment fade-in">
<h4 id="post20192024-symbiosis-breaks-down">Post‑2019/2024: Symbiosis breaks down</h4>
</div>
<ul>
<li class="fragment"><p>SNP weakened: leadership crisis, indyref fatigue, governing wear‑and‑tear</p></li>
<li class="fragment"><p>Scottish Conservatives lose credibility: UK‑wide scandals, Brexit delivery, and UK “muscular unionism” alienate voters</p></li>
<li class="fragment"><p>Salience of the constitutional issue stops rising and begins to diffuse into wider frustration with both camps</p></li>
</ul>
</div><div class="fragment fade-in">
<h4 id="result">Result</h4>
</div>
<ul>
<li class="fragment">Constitutional polarisation erodes to let new player, like the anti‑establishment, anti‑SNP party enter the field (Reform) under proportional rules</li>
</ul>
</section>
<section id="demand-is-structural-supply-is-contingent" class="slide level2">
<h2>Demand is Structural, Supply is Contingent</h2>
<ol type="1">
<li class="fragment"><strong>Same demand, different supply vehicles:</strong>
<ul>
<li class="fragment">2010: BNP (563k votes, extremist) vs UKIP (919k votes, sovereigntist)</li>
<li class="fragment">Underlying economic/cultural anxiety is similar</li>
<li class="fragment">Distinct framings → divergent electoral trajectories</li>
</ul></li>
<li class="fragment"><strong>Supply parties recycle (~15-20 years):</strong>
<ul>
<li class="fragment">BNP peaks mid‑2000s → hits extremism ceiling, collapses</li>
<li class="fragment">UKIP peaks 2015 → achieves Brexit goal, becomes redundant</li>
<li class="fragment">Reform rises post‑2022 → reactivates same reservoir of discontent</li>
<li class="fragment">Parties are disposable vessels; underlying demand is durable</li>
</ul></li>
<li class="fragment"><strong>Supply spreads to new regions:</strong>
<ul>
<li class="fragment">England: BNP → UKIP → Reform as successive carriers</li>
<li class="fragment">Scotland: long blocked by constitutional salience → opening after SNP–Tory symbiosis breaks</li>
<li class="fragment">Same demand, different institutional and territorial opportunity structures</li>
</ul></li>
</ol>
</section></section>
<section>
<section id="part-3-who-votes-far-right-in-the-uk" class="title-slide slide level1 center">
<h1>Part 3: Who Votes Far-Right in the UK?</h1>

</section>
<section id="ess-demographics-who-votes-far-right-in-the-uk-rounds-1-11" class="slide level2">
<h2>ESS Demographics: Who Votes Far-Right in the UK? (Rounds 1-11)</h2>

<img data-src="Lecture_Week3_UK_Restructured-2_files/figure-revealjs/unnamed-chunk-1-1.png" width="1056" class="r-stretch"><aside class="notes">
<p><strong>What we’re looking at:</strong></p>
<p>This shows differences from reference categories across nine demographic dimensions:</p>
<p><strong>Reference baseline (0 line):</strong> - Female (gender reference) - Age 18-34 (age reference) - Liberal on immigration (reference) - High trust in politicians (reference) - Political center (reference) - Comfortable income (reference) - High education (reference) - Urban location (reference) - Professional/managers (reference)</p>
<p><strong>Dennison &amp; Goodwin framework predicts:</strong> - Economic insecurity → lower education, working class (+) - Age → older voters (55-70) (+) - Cultural anxiety → restrictive immigration attitudes (+) - Political distrust → low trust in politicians (+) - Location → rural/small town (+)</p>
<p><strong>Is the data pattern as expected?</strong></p>
<p>Yes: Working class +, lower education +, restrictive immigration attitudes +, older voters +, rural +, low political trust +</p>
<p>This confirms: Multiple dimensions interact (economic + cultural + political).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="electoral-marginality-policy-victory-2010-2016" class="slide level2">
<h2>Electoral Marginality &amp; Policy Victory (2010-2016)</h2>

<img data-src="Lecture_Week3_UK_Restructured-2_files/figure-revealjs/unnamed-chunk-2-1.png" width="1152" class="r-stretch"><aside class="notes">
<p><strong>The Real Paradox (not what the chart shows):</strong></p>
<p>The chart shows something MECHANICAL, not paradoxical: - FPTP suppresses representation → predictable, by design - PR enables proportional representation → also predictable, by design - This is HOW these systems work, not surprising</p>
<p><strong>The ACTUAL paradox is elsewhere:</strong></p>
<ol type="1">
<li><strong>Electoral marginality via FPTP (2015):</strong>
<ul>
<li>3.88 million votes (12.6%) → 1 seat</li>
<li>Massively unrepresented</li>
</ul></li>
<li><strong>But policy victory (2016):</strong>
<ul>
<li>Won Brexit referendum</li>
<li>Forced government hand</li>
<li>Achieved biggest political goal without parliament</li>
</ul></li>
</ol>
<p><strong>This contradicts an assumption:</strong> - “Parliamentary seats = political power” - UKIP proves: Electoral marginality ≠ policy irrelevance - Non-electoral pathways (activism, public campaign, political pressure) can matter more than seats</p>
<p><strong>This is genuinely puzzling:</strong> - How do parties without seats win referendums? - How do marginal parties force major policy shifts? - What does this tell us about far-right influence beyond parliament?</p>
<p>This will be crucial for Week 9 (normalization): Far-right influence operates through multiple channels, not just electoral representation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="from-strategy-to-system-what-the-uk-case-shows" class="slide level2">
<h2>From Strategy to System: What the UK Case Shows</h2>
<ul>
<li class="fragment"><p>Same grievances, different party framings and images → different voter coalitions.</p></li>
<li class="fragment"><p>Same voters, different electoral rules → different representation in office.</p></li>
<li class="fragment"><p>Weak in parliament, but strong through referendums and discourse → major policy change (Brexit).</p></li>
</ul>
<div class="fragment fade-in">
<p><strong>Key questions</strong>:</p>
</div>
<ol type="1">
<li class="fragment"><p>Which party strategies unlock broad support among those worried about immigration and Europe?</p></li>
<li class="fragment"><p>How do electoral rules and referendums channel that support into real policy outcomes?</p></li>
</ol>
</section>
<section id="key-references" class="slide level2">
<h2>Key References</h2>
<p><strong>Primary Source (Electoral Data):</strong></p>
<p>Goodwin, M. J., &amp; Dennison, J. (2018). The Radical Right in the United Kingdom. In J. Rydgren (Ed.), <em>The Oxford Handbook of the Radical Right</em> (pp.&nbsp;530-552). Oxford University Press.</p>
<p>Ford, Robert, and Matthew J Goodwin. 2010. ‘Angry White Men: Individual and Contextual Predictors of Support for the British National Party’. Political studies 58(1): 1–25. doi:10.1111/j.1467-9248.2009.00829.x.</p>
<p><strong>Data Sources:</strong></p>
<ul>
<li><p>Electoral data: ParlGov (1994-2024)</p></li>
<li><p>Demographic data: European Social Survey (Rounds 1-11)</p></li>
<li><p>Scottish polling: Scottish Election Study, Scottish Opinion Monitor</p></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/chrisvrakopoulos\.github\.io\/Far-Right-UoE\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>